# Generated by Django 3.2.4 on 2021-06-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='isfav',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
